In [2]:
from google.colab import drive
drive.mount('/content/drive')

import os
os.chdir("/content/drive/My Drive/Colab Notebooks/deeplearning_with_pytorch")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


# Tensors

In [3]:
import torch
a = torch.ones(3)
a

tensor([1., 1., 1.])

In [4]:
# indexing is just same as list
a[1]

tensor(1.)

In [5]:
float(a[1]) # to float

1.0

In [6]:
a[2] = 2.0 # write over is the same
a

tensor([1., 1., 2.])

In [7]:
points = torch.zeros(6)
points[0] = 4.0
points[1] = 1.0
points[2] = 5.0
points[3] = 3.0
points[4] = 2.0
points[5] = 1.0


In [8]:
points = torch.tensor([4.0, 1.0, 5.0, 3.0, 2.0, 1.0])
points

tensor([4., 1., 5., 3., 2., 1.])

In [9]:
float(points[0]), float(points[1])

(4.0, 1.0)

In [10]:
# multi dimensional tensor is also possible
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [11]:
points.shape

torch.Size([3, 2])

In [12]:
points = torch.zeros(3, 2)

In [13]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [14]:
points[0, 1] # matrix indexing

tensor(1.)

In [15]:
points[0] # outputs a row

tensor([4., 1.])

In [16]:
# pytorch tensor is stored as an one dimensional list in C
# which is called storage
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.FloatStorage of size 6]

In [17]:
points_storage = points.storage()
points_storage[0] # access just like a list

4.0

In [18]:
points.storage()[1] # alternatively

1.0

In [19]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points_storage = points.storage()
points_storage[0] = 2.0 # this changes value in storage
points

tensor([[2., 1.],
        [5., 3.],
        [2., 1.]])

In [20]:
# what we see is a view of the storage
# shows different view depending on stride(column) and offset(row)
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1]
second_point.storage_offset()

2

In [21]:
second_point.size()

torch.Size([2])

In [22]:
second_point.shape

torch.Size([2])

In [23]:
points.stride()

(2, 1)

In [24]:
second_point = points[1]
second_point.size()

torch.Size([2])

In [25]:
second_point.storage_offset(), second_point.stride()

(2, (1,))

In [26]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1]
second_point[0] = 10.0 # changes the original tensor
points

tensor([[ 4.,  1.],
        [10.,  3.],
        [ 2.,  1.]])

In [27]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1].clone() # make clone for deep copy
second_point[0] = 10.0
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [28]:
# transpose
points_t = points.t()
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [29]:
id(points.storage()) == id(points_t.storage()) # same memory address, only view changed

True

In [30]:
points.stride()

(2, 1)

In [31]:
points_t.stride()

(1, 2)

In [32]:
# multidimensional matrix transpose is also possible
some_t = torch.ones(3, 4, 5)
transpose_t = some_t.transpose(0, 2)
some_t.shape

torch.Size([3, 4, 5])

In [33]:
transpose_t.shape

torch.Size([5, 4, 3])

In [34]:
some_t.stride()

(20, 5, 1)

In [35]:
transpose_t.stride()

(1, 5, 20)

In [36]:
points.is_contiguous()

True

In [37]:
points_t.is_contiguous()

False

In [38]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points_t = points.t()
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [39]:
points_t.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.FloatStorage of size 6]

In [40]:
points_t.stride()

(1, 2)

In [41]:
# make new tensor contiguous
points_t_cont = points_t.contiguous()
points_t_cont

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [42]:
points_t_cont.stride()

(3, 1)

In [43]:
points_t_cont.storage()

 4.0
 5.0
 2.0
 1.0
 3.0
 1.0
[torch.FloatStorage of size 6]

In [44]:
# dtypes for tensor
# specify by dtype=
double_points = torch.ones(10, 2, dtype=torch.double)
short_points = torch.tensor([[1, 2], [3, 4]], dtype=torch.short)

In [45]:
short_points.dtype

torch.int16

In [46]:
# alternative method
double_points = torch.zeros(10, 2).double()
short_points = torch.ones(10, 2).short()

In [47]:
double_points = torch.zeros(10, 2).to(torch.double)
short_points = torch.ones(10, 2).to(dtype=torch.short)

In [48]:
points_64 = torch.rand(5, dtype=torch.double) 
points_short = points_64.to(torch.short)
points_64 * points_short # tensor will be converted to longer format

tensor([0., 0., 0., 0., 0.], dtype=torch.float64)

In [49]:
# slicing works just like list
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])

points[1:]
points[1:, :]
points[1:, 0]
points[None] # prints all

tensor([[[4., 1.],
         [5., 3.],
         [2., 1.]]])

In [50]:
# conversion to numpy array
points = torch.ones(3, 4)
points_np = points.numpy()
points_np

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [51]:
# convert back to tensor
points = torch.from_numpy(points_np)
points

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [52]:
# zero_ will zero out everything
points.zero_()

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [53]:
## Saving to tensor
torch.save(points, './data/p1ch3/ourpoints.t')

In [54]:
with open('./data/p1ch3/ourpoints.t','wb') as f:
   torch.save(points, f)

In [55]:
points = torch.load('./data/p1ch3/ourpoints.t')

In [56]:
points

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [57]:
with open('./data/p1ch3/ourpoints.t','rb') as f:
   points = torch.load(f)

points

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [58]:
# using h5py

import h5py

f = h5py.File("./data/p1ch3/ourpoints.hdf5", 'w')
dset = f.create_dataset('coords', data=points.numpy()) # save as numpy
f.close()

In [59]:
f = h5py.File('./data/p1ch3/ourpoints.hdf5', 'r')
dset = f['coords']
last_points = dset[-2:]
f.close()

In [60]:
# sending data to gpu
points_gpu = points.to(device='cuda')

In [61]:
points_gpu

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]], device='cuda:0')

## Named tensors

In [62]:
_ = torch.tensor([0.2126, 0.7152, 0.0722], names=['c']) # names are experimental

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /pytorch/c10/core/TensorImpl.h:934.)
  """Entry point for launching an IPython kernel.


In [63]:
img_t = torch.randn(3, 5, 5) # shape [channels, rows, columns]
weights = torch.tensor([0.2126, 0.7152, 0.0722])

In [64]:
batch_t = torch.randn(2, 3, 5, 5) # shape [batch, channels, rows, columns]

In [65]:
img_gray_naive = img_t.mean(-3)
batch_gray_naive = batch_t.mean(-3)
img_gray_naive.shape, batch_gray_naive.shape

(torch.Size([5, 5]), torch.Size([2, 5, 5]))

In [68]:
unsqueezed_weights = weights.unsqueeze(-1).unsqueeze(-1)
img_weights = (img_t * unsqueezed_weights)
batch_weights = (batch_t * unsqueezed_weights)
img_gray_weighted = img_weights.sum(-3)
batch_gray_weighted = batch_weights.sum(-3)
batch_weights.shape, batch_t.shape, unsqueezed_weights.shape

(torch.Size([2, 3, 5, 5]), torch.Size([2, 3, 5, 5]), torch.Size([3, 1, 1]))

In [69]:
img_gray_weighted_fancy = torch.einsum('...chw,c->...hw', img_t, weights) # einsum clarifies multidimensional product
batch_gray_weighted_fancy = torch.einsum('...chw,c->...hw', batch_t, weights)
batch_gray_weighted_fancy.shape

torch.Size([2, 5, 5])

In [70]:
weights_named = torch.tensor([0.2126, 0.7152, 0.0722], names=['channels'])
weights_named

tensor([0.2126, 0.7152, 0.0722], names=('channels',))

In [71]:
img_named = img_t.refine_names(..., 'channels', 'rows', 'columns')
batch_named = batch_t.refine_names(..., 'channels', 'rows', 'columns')
print(img_named)
print(batch_named)

tensor([[[ 0.3759,  1.3372, -0.5088, -0.2746,  1.8038],
         [ 0.2834, -0.6043,  0.1461, -2.6975, -0.3126],
         [-1.2169,  0.4086,  0.5313,  1.2759, -0.5130],
         [-0.1011,  0.7794,  1.3288,  2.5763, -0.0804],
         [-0.0578, -0.7342, -0.1897, -1.8423, -0.2177]],

        [[-1.0919,  0.6016, -1.0815, -0.0651,  0.2897],
         [-2.2819, -0.8314,  0.1250,  1.4047, -0.3938],
         [-0.7125,  1.7061,  0.3815, -1.1197,  0.2166],
         [-0.9421,  0.3697,  0.8468,  0.1997,  0.0531],
         [-0.4625, -1.1775,  1.5056, -1.2525,  1.5091]],

        [[-1.8308, -0.1914,  1.2738, -0.3223,  0.6716],
         [-2.1389,  0.5767, -0.1933,  0.5600, -0.7085],
         [ 0.1423, -1.4248,  1.5745,  1.2453, -0.5951],
         [-0.0327, -0.3203,  0.7636,  1.6078, -1.9058],
         [-1.3522, -0.2957,  0.1216, -0.1457, -0.8651]]],
       names=('channels', 'rows', 'columns'))
tensor([[[[-9.6767e-01,  1.4552e-03, -2.3000e+00,  3.2872e-01,  5.2991e-01],
          [-6.3967e-01, -2.7821

In [72]:
weights_aligned = weights_named.align_as(img_named)
gray_named = (img_named * weights_aligned).sum('channels')
gray_named.shape, gray_named.names

(torch.Size([5, 5]), ('rows', 'columns'))

In [73]:
a = torch.tensor(list(range(9)))

In [74]:
b = a.view(3, 3)

In [75]:
b

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [76]:
b.stride()

(3, 1)

In [77]:
c = b[1:, 1:]

In [78]:
c

tensor([[4, 5],
        [7, 8]])

In [79]:
c.stride() # stride is still 3 because it references b

(3, 1)